# Generated by Django 2.0 on 2017-12-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hashcat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_ressource', models.CharField(max_length=30)),
                ('hashfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hashcat.Hashfile')),
            ],
        ),
    ]
