# Generated by Django 2.0 on 2017-12-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cracked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=190, null=True)),
                ('password', models.CharField(max_length=190)),
                ('hash', models.CharField(max_length=190, null=True)),
                ('password_len', models.IntegerField()),
                ('password_charset', models.CharField(max_length=100)),
                ('password_mask', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hashfile', models.CharField(max_length=30)),
                ('crackedfile', models.CharField(max_length=30)),
                ('hash_type', models.IntegerField()),
                ('line_count', models.IntegerField()),
                ('cracked_count', models.IntegerField(default=0)),
                ('username_included', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('potfile_line_retrieved', models.IntegerField()),
                ('hashfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hashcat.Hashfile')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nodes.Node')),
            ],
        ),
        migrations.AddField(
            model_name='cracked',
            name='hashfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hashcat.Hashfile'),
        ),
        migrations.AddIndex(
            model_name='cracked',
            index=models.Index(fields=['hashfile_id'], name='hashfileid_id_index'),
        ),
    ]
