# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='ip',
            new_name='hostname',
        ),
    ]
