# Generated by Django 2.0.3 on 2018-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('output_lines', models.IntegerField(null=True)),
                ('output_file', models.TextField()),
                ('json_search_info', models.TextField()),
            ],
        ),
    ]
