# Generated by Django 3.0.7 on 2020-06-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hash',
            name='hashfileid_hash_index',
        ),
        migrations.RemoveIndex(
            model_name='hash',
            name='hash_index',
        ),
    ]
