# Generated by Django 3.0.7 on 2020-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0002_auto_20200610_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='hash',
            field=models.TextField(null=True),
        ),
    ]
