# Generated by Django 2.0.3 on 2018-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='processing_time',
            field=models.IntegerField(null=True),
        ),
    ]
