# Generated by Django 2.1 on 2018-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0003_search_processing_time'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hash',
            name='hashfileid_index',
        ),
        migrations.RemoveIndex(
            model_name='hash',
            name='hashfileid_hash_index',
        ),
        migrations.AddIndex(
            model_name='hash',
            index=models.Index(fields=['hashfile'], name='hashfileid_index'),
        ),
        migrations.AddIndex(
            model_name='hash',
            index=models.Index(fields=['hashfile', 'hash'], name='hashfileid_hash_index'),
        ),
    ]
