# Generated by Django 2.0.3 on 2018-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0003_search_processing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_type',
            field=models.IntegerField(default=2),
        ),
    ]
