# Generated by Django 3.0.7 on 2020-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0004_auto_20200610_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('lines', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('lines', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('lines', models.IntegerField()),
            ],
        ),
    ]
