# Generated by Django 2.0.3 on 2018-07-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0004_session_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_timestamp',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
