# Generated by Django 2.0.3 on 2018-07-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashcat', '0005_session_end_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_timestamp',
        ),
    ]
