# Generated by Django 3.0.7 on 2020-06-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0002_auto_20200623_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
