version: '3.7'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - variables.env
    volumes:
      - ./Files:/webhashcat/Files
    depends_on:
      - redis
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - variables.env

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A WebHashcat worker -B -l info
    env_file:
      - variables.env
    volumes:
      - ./Files:/webhashcat/Files
    depends_on:
      - redis
      - db
