version: '3.7'

services:
  db:
    image: mysql:8.0.32-debian
    env_file:
      - variables.env
    networks:
      - webhashcat
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    networks:
      - webhashcat
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 5s
      retries: 10

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - variables.env
    volumes:
      - ./Files:/webhashcat/Files
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - webhashcat

  celery:
    build: .
    command: celery -A WebHashcat worker -B -l info
    env_file:
      - variables.env
    volumes:
      - ./Files:/webhashcat/Files
    depends_on:
      - redis
      - db
    networks:
      - webhashcat
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

networks:
  webhashcat:
    name: webhashcat
    driver: bridge
